### ISSUE TITLE
2017.05.15 (월) 논의

### ISSUE THREAD

**Issue by junho85** [yamujine/artmatch#341]
## 개요
장소에서 상태가 작품모집중이더라도 모집 기간이 지나면 기간만료? 같은게 나오도록

**Comment by kimtree** [comment]
### 작업 필요한 사항
#### 1차 (2017.05.15 ~)
1. 전시 등록 페이지 (전시명 / 날짜 / 상태 / 작품 수)
주소: /places/exhibitions/<place_id> 
![image](https://cloud.githubusercontent.com/assets/1219373/26057976/c4f75f06-39b6-11e7-991c-c9e73f697e70.png)
PAY_추가스펙1의 두번째
    - rename: 전시 관리 페이지 
    - 백엔드: 전시 관리 페이지 추가 필요 & 추가/수정/삭제 API 개발 필요
    - 프론트: UI 상에서 추가시 form 맨 위에 추가되게, 나머지 부분은 댓글 입력란과 비슷한 방식으로 개발
2. 작품 지원시 지원 이유 넣기
3. 장소 디테일
    - 전시 리스트
    - 지금 전시중
#### 2차 (2017.xx.xx ~)
1. 마이페이지 > 장소 소유자 > 지원한 작품 선택하기 페이지 ( 전시명에 장소 - 전시명 으로 드랍다운 선택 )
2. 마이페이지 > 작품 소유자 > 지원한 작품 리스트 보기 페이지 (지원 취소 기능)

### 확인 필요 사항
https://zpl.io/Z1HCqUu
- 마이페이지 > 작품 소유자 > 지원한 작품 리스트에서 장소명 표시 여부 (지원한 전시 제목만 보고는 장소를 알 수 없음)
- 마이페이지 > 작품 소유자 > 지원한 작품 채택시

**Comment by kimtree** [comment]
**2차 온라인 미팅 2017.5.21 오후 3시**

**Comment by junho85** [comment]
목표: 5.28 (일) 까지 추가스펙1 이슈 완료
중간점검미팅: 5.21 (일) 오후 3시

참고
남우님은 이번주 금요일 시험
진만님도 이번주 주말부터 작업
지수님은 목요일 부터 2주간 출국

**Comment by kimtree** [comment]
다음 미팅: **5월 28일(일) 오후 3시** 구글 톡 접속!
1차 진행 사항 ASAP 진행
- 백엔드 빨리 진행해서 뒷 태스크 밀리지 않도록
- 마크업 공백은 준호님과 현영님이 노력해주시기로(?)

**Comment by junho85** [comment]
할일

장소상세
* [x] 백엔드 - 지금전시중이에요  https://github.com/yamujine/artmatch/issues/344 - 남우
* [ ] 프론트 - 전시 목록, 지금 전시중 https://github.com/yamujine/artmatch/issues/356 - 준호

전시등록페이지
* [ ] 마크업 - 전시등록페이지 https://github.com/yamujine/artmatch/issues/357 - 진만
* [ ] 프론트 - 전시등록페이지 https://github.com/yamujine/artmatch/issues/359 - 현영

지원하기페이지
* [ ] 마크업 - 지원하기페이지 이유추가 https://github.com/yamujine/artmatch/issues/358 - 진만

**Comment by kimtree** [comment]
다음 미팅: **6월 4일(일) 오후 3시** 구글 톡 접속!
1차 진행 사항 재 마무리!

**Comment by junho85** [comment]
TODO
* [ ] 지원하기를 장소기준에서 진시회기준으로 변경 해야 됨
기존: 장소기준 /places/apply/80
수정: 전시회 기준 ex) /places/80/exhibitions/??/apply

**Comment by kimtree** [comment]
다음 미팅: **6월 11일(일) 오후 3시** 구글 톡 접속!
- 1차 진행 사항 재 마무리!
- 준호님: 마크업
- 현영님: 프론트엔드
- 지수님: 열려있는 Pull Request 2건 해결 및 1차 진행사항 백엔드 버그 수정!
- 남우: 기 말 고 사 시 험 기 간 !!

기획 확인 사항은 이슈로 등록 후 철혁님께 카톡(?)

**Comment by kimtree** [comment]
다음 미팅: **6월 18일(일) 오후 3시** 구글 톡 접속!

* 1차 / 2차 진행사항 가능한 부분 쭉 진행
* 모든 팀 전체 한번 다같이 모여야 할 듯! 7월 중?
* 준호님: 마크업
* 현영님: 프론트엔드
* 지수님: 서버 쪽 FB SDK / 마이페이지 기반 작업
* 남우: 기 말 고 사 시 작..........

**Comment by junho85** [comment]
기획이슈 답변 공유
기획 - 장소 상세 > 전시 목록 표시 #364
https://github.com/yamujine/artmatch/issues/364

남우님 시험기간: 23일 까지. 그런데 끝나고 주말에 행사 준비 있다고 함.
지수님: 19일(월) 부터 출근

기획 확인 사항은 이슈로 등록 후 철혁님께 카톡

마일스톤: POST-CAMP 1차 https://github.com/yamujine/artmatch/milestone/5
[DB] 스키마 변경 #368

**Comment by junho85** [comment]
* 남우: 시험 목요일 끝남. PR 리뷰
* 진만: 시험 화요일 끝남. 1차 작업 한거 리뷰. 2차 마크업 진행.
  * 마크업 - 장소제공자 마이페이지 > 지원작가 #374
  * 마크업 - 작가 마이페이지 -> 지원한 전시 #375
* 준호: 지원하기 마크업
  * 마크업 - 장소 상세 > 전시 등록 페이지 개선 #373
* 현영: 전시회 프론트
  * 프론트 - 장소 상세 > 전시 등록 페이지 #359
* 지수: PR 확인 기다림 / 마이페이지 작업 진행

**Comment by kimtree** [comment]
다음 미팅: **6월 25일(일) 오후 3시** 구글 톡 접속!

**Comment by nablyy** [comment]
## 한거
- 프론트 : 장소 페이지 지금전시중 슬라이드 만드는 중

## 할거
- 프론트 : 장소상세 > 전시목록표시 슬라이드 마저 완성
- 프론트 : 장소상세 > 전시 등록 페이지

## 이슈
- #364 작품 개수 관련 기획 확인 필요
- 지원하기 route
    - 현재 전시별 아니고 장소별로만 지원됨 
    -> 지원하기 링크에 문제있음 일단 exhibitions/(:num)/apply 로 처리해놓겠음(반영안되어서 404)

**Comment by junho85** [comment]
## 한거
* 마크업 - 장소 상세 > 전시 등록 페이지 개선 #373 - 진행중
  * static url 생성 로직 수정
  * 지원하기 route 수정
    * places/(:num)/apply -> exhibitions/(:num)/apply
  * Exhibition Controller 분리

## 할거
* 마크업 - 장소 상세 > 전시 등록 페이지 개선 #373 - 계속 진행
  * 마크업 작업
  * places 기준이 아니고 exhibitions 기준으로 바뀐 부분에 대한 처리

## 이슈
* 장소 등록에서 대관료 부분도 전시회 등록에 들어가는 것으로 알고 있는데 장소 등록 UI 에 남아 있어서 확인 요청 to @기획, @디자인
  * https://app.zeplin.io/project/589f368808d7261dc3f30fff/screen/58ab2bcad93b58ed92d37a10

**Comment by genie-youn** [comment]
### 한일
  MyPage 분리작업 진행중

---
### 할일
  PR Review 반영
  MyPage 분리작업 이어서

**Comment by kimtree** [comment]
## 할거
- #368 [DB] 스키마 변경

**Comment by kimtree** [comment]
* 남우: 페이스북 SDK PR 리뷰 / #381 장소 추가/수정시 전시 생성 로직 제거
* 진만: #373 #358 #357 이미 작업 되어 있으면 개선, 안되어 있으면 마크업 필요! / #359 지원!
* 준호: #373 기존 작업 진행 및 진만님과 점검!
* 현영: #367 회원가입시 아이디 길이 체크 점검 / #356 장소 상세 전시 정보 / #359 전시 등록페이지 기능 추가
* 지수: #335 Facebook SDK 관련 오류 점검 / #306 전화번호로 가입한 회원도 가입 잘 되도록 처리

프론트 버그: #298 / 작품 등록시 버그: #274 

- 전체 프로세스 한 번 점검 후 버그 있으면 열심히 올려주세요!!

다음 미팅: **7월 9일(일)** 오프 미팅 전 또는 후 모여서 배포 후 버그 헌팅(?)
